version: '2'
services:
  rabbitmq:
    image: mdaichang/rabbitmq-conf:0.2.1
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: rabbitmq-base,rabbitmq-datavolume
    volumes_from:
      - rabbitmq-datavolume
    environment:
      RABBITMQ_NET_TICKTIME: ${net_ticktime}
      RABBITMQ_CLUSTER_PARTITION_HANDLING: ${cluster_partition_handling}
      CONFD_ARGS: ${confd_args}
      RABBITMQ_DEFAULT_USER: ${rabbitmq_default_user}
      RABBITMQ_DEFAULT_PASS: ${rabbitmq_default_pass}
      RABBITMQ_DEFAULT_VHOST: ${rabbitmq_default_vhost}
  rabbitmq-datavolume:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - /etc/rabbitmq
      - /opt/rancher/bin
    network_mode: "none"
    entrypoint: /bin/true
    image: rabbitmq:3.6-management
  rabbitmq-base:
    labels:
      io.rancher.container.hostname_override: container_name
    image: rabbitmq:3.6-management
    restart: always
    volumes_from:
      - rabbitmq-datavolume
    network_mode: "container:rabbitmq"
    entrypoint:
      - /opt/rancher/bin/run.sh
    environment:
      RABBITMQ_ERLANG_COOKIE: ${erlang_cookie}
